export const startingPosition = [
    ["bR", 1, 8],
    ["bN", 2, 8],
    ["bB", 3, 8],
    ["bQ", 4, 8],
    ["bK", 5, 8],
    ["bB", 6, 8],
    ["bN", 7, 8],
    ["bR", 8, 8],
    ["bP", 1, 7],
    ["bP", 2, 7],
    ["bP", 3, 7],
    ["bP", 4, 7],
    ["bP", 5, 7],
    ["bP", 6, 7],
    ["bP", 7, 7],
    ["bP", 8, 7],
    ["wP", 1, 2],
    ["wP", 2, 2],
    ["wP", 3, 2],
    ["wP", 4, 2],
    ["wP", 5, 2],
    ["wP", 6, 2],
    ["wP", 7, 2],
    ["wP", 8, 2],
    ["wR", 1, 1],
    ["wN", 2, 1],
    ["wB", 3, 1],
    ["wQ", 4, 1],
    ["wK", 5, 1],
    ["wB", 6, 1],
    ["wN", 7, 1],
    ["wR", 8, 1],
];

export const startingFEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
